name: Build flask docker image
on: 
    push:
         branches:
            - main
    workflow_dispatch: # mannual trigger

jobs:
     build:
        name: Build Docker image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code 
              uses: actions/checkout@v3

            - name: Set up python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.12'

            - name: setup AWS creds
              uses: aws-actions/configure-aws-credentials@v2
              with:
                 aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                 aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                 aws-region: us-east-1
              

            - name: Setup docker buildx
              uses: docker/setup-buildx-action@v2
             
            - name: Login to Dockerhub
              uses: docker/login-action@v2
              with:
                 username: ${{ secrets.DOCKER_USERNAME }}
                 password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Build and Push Docker image
              uses: docker/build-push-action@v5
              with:
                 context: .
                 push: true
                 tags: tejalmanekar23/flask-app:latest
            - name: deploy  to kubernates  
              run: |
                 kubectl apply -f k8s/secrets.yaml
                 kubectl apply -f k8s/deployment.yaml
                 kubectl apply -f k8s/service.yaml

